# Generated by Django 5.1.4 on 2025-01-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_activity_additional_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='content_object',
        ),
        migrations.AddField(
            model_name='activity',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
