# Generated by Django 5.1.4 on 2024-12-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='activity',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
