# Generated by Django 5.1.4 on 2024-12-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_activity_action_alter_activity_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('profile_update', 'Alteração de Perfil'), ('image_upload', 'Upload de Imagem')], max_length=50),
        ),
    ]
