# Generated by Django 5.1.4 on 2025-02-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_medicalimage_diagnosis_delete_diagnosis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalimage',
            name='diagnosis',
        ),
        migrations.AddField(
            model_name='activity',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalimage',
            name='description',
            field=models.TextField(),
        ),
    ]
