# Generated by Django 5.1.4 on 2025-03-13 10:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_medicalimage_diagnosis_activity_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalimage',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
