# Generated by Django 5.1.4 on 2025-03-28 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_medicalimage_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('profile_update', 'Profile Change'), ('image_upload', 'X-Ray Uploaded')], max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='accounts.patient'),
        ),
    ]
